# Generated by Django 4.2.2 on 2023-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('last_name', models.TextField()),
                ('cereal', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('J', 'jumbo')], max_length=1)),
            ],
        ),
    ]
