# Generated by Django 4.2.2 on 2023-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0002_alter_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
