# Generated by Django 4.2.2 on 2023-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0003_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
