# Generated by Django 4.2.2 on 2023-07-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0004_alter_nota_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
